## Each new term in the Fibonacci sequence is generated by adding the previous 
## two terms. By starting with 1 and 2, the first 10 terms will be:
## 1,2,3,5,8,13,21,34,55,89,..
## By considering the terms in the Fibonacci sequence whose values do not exceed N, 
## find the sum of the even-valued terms.

## Sample Input
## 10
## 100

## Sample Output
## 10
## 44


import java.util.Scanner;

public class EvenFibonacci {

	public static void main(String[] args) {
		Scanner in = new Scanner(System.in);
		System.out.println("Enter the length");
		long length = in.nextInt();
		for (long i = 0; i < length; i++) {
			System.out.println("Enter the nth number ");
			long n = in.nextLong();
			System.out.println(evenFibonacci(n));
		}
	}

	public static long evenFibonacci(long n) {
		long n3 = 2; // 3rd number
		long n6 = 0; // 6th number
		long result = 2;
		long sum = 0;
		while (result <= n) {
			sum = sum + result;
			result = (4 * n3) + n6;
			n6 = n3;
			n3 = result;
		}
		return sum;
	}
}
